CREATE DATABASE gamelounge;

\c gamelounge;

CREATE TABLE games (
    id SERIAL PRIMARY KEY,
    image_url TEXT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    rating INT,
    genre1 VARCHAR(50),
    genre2 VARCHAR(50),
    age_rating INT,
    duration INT,
    num_players INT,
    developer VARCHAR(100),
    comment1 TEXT,
    comment2 TEXT
);

INSERT INTO games (image_url, name, description, rating, genre1, genre2, age_rating, duration, num_players, developer, comment1, comment2) VALUES
('dobble.png', 'Dobble', 'Jogo de cartas rápido onde os jogadores devem encontrar o símbolo em comum entre duas cartas.', 5, 'Cartas', 'Observação', 6, 15, 8, 'Asmodee', 'Viciante! Ótimo para jogar com amigos e família.', 'Simples de aprender e perfeito para todas as idades.'),
('uno.png', 'UNO', 'Clássico jogo de cartas em que o objetivo é ser o primeiro a se livrar de todas as cartas.', 5, 'Cartas', 'Estratégia', 7, 30, 10, 'Mattel', 'Diversão garantida para qualquer idade.', 'Um clássico! Cuidado pra não perder as amizades no caminho.'),
('tgcqp.png', 'Taco Gato Cabra Queijo Pizza', 'Jogo de cartas rápido e caótico onde os jogadores precisam bater na carta correta no momento certo.', 4, 'Cartas', 'Festa', 7, 15, 8, 'Blue Orange Games', 'Rende muitas risadas e confusões!', 'Perfeito para o grupo de amigos.'),
('dixit.png', 'Dixit', 'Jogo criativo e visual onde os jogadores usam pistas para adivinhar cartas ilustradas.', 5, 'Tabuleiro', 'Criatividade', 8, 40, 6, 'Libellud', 'As ilustrações são lindas.', 'Perfeito para quem gosta de usar a criatividade.'),
('trio.png', 'Trio', 'Jogo de cartas estratégico em que o objetivo é formar trios de números.', 4, 'Cartas', 'Estratégia', 7, 20, 6, 'Repos Production', 'Fácil de aprender e muito competitivo!', 'Ideal para quem gosta de desafios rápidos.'),
('jenga.png', 'Jenga', 'Jogo de habilidade e equilíbrio onde os jogadores retiram blocos de madeira de uma torre.', 5, 'Habilidade', 'Clássico', 6, 15, 8, 'Hasbro', 'Tensão e diversão a cada jogada!', 'Um clássico indispensável para qualquer reunião.'),
('coup.png', 'Coup', 'Jogo de blefe e estratégia onde os jogadores assumem papéis secretos.', 4, 'Cartas', 'Estratégia', 10, 15, 6, 'Indie Boards & Cards', 'Adoro o aspecto de blefe do jogo.', 'Rápido e cheio de reviravoltas.'),
('perfilexpress.png', 'Perfil Express', 'Jogo de perguntas rápidas onde os jogadores tentam adivinhar respostas com base em perfis.', 4, 'Perguntas', 'Social', 12, 8, 6, 'Cranio Creations', 'Ótimo para conhecer melhor os amigos!', 'Perfeito para festas e encontros sociais.'),
('catan.png', 'Catan', 'Jogo de estratégia onde os jogadores colonizam uma ilha, coletam recursos e negociam.', 5, 'Tabuleiro', 'Estratégia', 10, 90, 4, 'Kosmos', 'Um dos melhores jogos de estratégia.', 'Repleto de negociações e decisões estratégicas.'),
('imagemeacao.png', 'Imagem e Ação', 'Jogo clássico onde os jogadores desenham ou atuam palavras para que a equipe adivinhe.', 4, 'Desenho', 'Festa', 8, 60, 16, 'Mattel', 'Diversão garantida para todas as idades!', 'Perfeito para festas em família ou com amigos.'),
('war.png', 'War', 'Jogo de estratégia militar onde os jogadores conquistam territórios.', 4, 'Tabuleiro', 'Estratégia', 10, 120, 6, 'Grow', 'Adoro a combinação de sorte e estratégia.', 'Um clássico que nunca sai de moda.'),
('storycubes.png', 'Story Cubes', 'Jogo criativo onde os jogadores lançam dados com imagens e criam histórias.', 5, 'Dados', 'Criatividade', 6, 30, 12, 'Rorys Story Cubes', 'Estimula a imaginação.', 'Perfeito para todas as idades e ocasiões.'),
('hamburgueriamaluca.png', 'Hamburgueria Maluca', 'Jogo de cartas onde os jogadores competem para montar hambúrgueres malucos.', 4, 'Cartas', 'Festa', 7, 20, 6, 'Red Glove', 'Divertido e rápido de jogar!', 'Ideal para quem gosta de jogos leves e engraçados.'),
('codigosecreto.png', 'Código Secreto', 'Jogo de palavras onde os jogadores dão pistas para adivinhar as palavras corretas.', 5, 'Palavras', 'Estratégia', 10, 15, 8, 'Czech Games Edition', 'Ótimo para exercitar o cérebro!', 'Perfeito para grupos que gostam de desafios mentais.'),
('lince.png', 'Lince', 'Jogo de observação rápida onde os jogadores competem para encontrar objetos escondidos.', 4, 'Observação', 'Família', 6, 15, 4, 'Devir', 'Rápido e divertido para todas as idades.', 'Excelente para desenvolver atenção e rapidez.'),
('monopoly.png', 'Monopoly', 'Clássico jogo de compra e venda de propriedades.', 4, 'Tabuleiro', 'Estratégia', 8, 120, 6, 'Hasbro', 'Um clássico que nunca sai de moda.', 'Ideal para longas sessões de jogo com amigos e família.'),
('tickettoride.png', 'Ticket to Ride', 'Jogo de estratégia onde os jogadores coletam cartas de trem para construir rotas.', 5, 'Tabuleiro', 'Estratégia', 8, 60, 5, 'Days of Wonder', 'Fácil de aprender e muito estratégico.', 'Perfeito para todas as idades e níveis de experiência.'),
('sixtix.png', 'Sixtix', 'Jogo de cartas onde os jogadores tentam formar sequências numéricas.', 4, 'Cartas', 'Estratégia', 7, 20, 6, 'Lúdilo', 'Rápido e cheio de estratégia!', 'Ideal para quem gosta de jogos de cartas desafiadores.'),
('tokaido.png', 'Tokaido', 'Jogo de tabuleiro onde os jogadores viajam pela estrada Tokaido no Japão.', 5, 'Tabuleiro', 'Aventura', 8, 60, 5, 'Funforge', 'Experiência relaxante e bonita.', 'Perfeito para quem gosta de jogos tranquilos e estratégicos.'),
('stella.png', 'Stella', 'Jogo de cartas onde os jogadores competem para coletar estrelas e completar objetivos.', 4, 'Cartas', 'Estratégia', 8, 30, 6, 'Lúdilo', 'Divertido e estratégico!', 'Ideal para quem gosta de jogos rápidos e desafiadores.'),
('micromacro.png', 'MicroMacro: Crime City', 'Jogo de tabuleiro onde os jogadores investigam cenas de crime detalhadas.', 5, 'Tabuleiro', 'Investigação', 10, 60, 4, 'Pegasus Spiele', 'Incrivelmente detalhado e envolvente.', 'Perfeito para fãs de mistério e investigação.'),
('ishtar.png', 'Ishtar', 'Jogo de tabuleiro onde os jogadores constroem e desenvolvem a cidade de Ishtar.', 4, 'Tabuleiro', 'Estratégia', 10, 90, 4, 'Lúdilo', 'Desafiador e muito estratégico!', 'Ideal para quem gosta de jogos complexos e envolventes.'),
('stickup.png', 'Stick Up!', 'Jogo de cartas onde os jogadores assumem o papel de ladrões tentando roubar joias.', 4, 'Cartas', 'Estratégia', 8, 20, 6, 'Red Glove', 'Divertido e cheio de reviravoltas!', 'Perfeito para quem gosta de jogos rápidos e estratégicos.'),
('noobjects.png', 'No Objects', 'Jogo de cartas onde os jogadores tentam adivinhar objetos com base em dicas.', 4, 'Cartas', 'Social', 7, 30, 8, 'Cranio Creations', 'Ótimo para conhecer melhor os amigos!', 'Perfeito para festas e encontros sociais.'),
('duna.png', 'Duna: Imperium', 'Jogo de tabuleiro estratégico baseado no universo de Duna.', 5, 'Tabuleiro', 'Estratégia', 12, 90, 4, 'Dire Wolf Digital', 'Incrível para fãs de Duna e jogos de estratégia.', 'Complexo e cheio de decisões táticas.'),
('passpass.png', 'Pass Pass', 'Jogo de cartas estratégico onde os jogadores competem jogando cartas para conquistar pontos.', 3, 'Cartas', 'Familiar', 8, 25, 3, 'PaperGames', 'Caixa resistente à abertura e fechamento constantes.', 'Caixa compacta, facilitando o transporte; materiais de alta qualidade.'),
('forsale.png', 'For Sale', 'Jogo de cartas rápido e estratégico onde os jogadores competem para comprar e vender propriedades.', 4, 'Cartas', 'Estratégia', 8, 30, 6, 'Lúdilo', 'Jogo com regras simples e partidas rápidas.', 'Componentes de alta qualidade e ótima experiência de jogo.'),
('dive.png', 'Dive', 'Jogo de cartas estratégico onde os jogadores assumem o papel de mergulhadores em busca de tesouros.', 3, 'Cartas', 'Estratégia', 10, 30, 4, 'Lúdilo', 'Jogo com regras fáceis e partidas dinâmicas.', 'Componentes de alta qualidade e ótima experiência de jogo.'),
('spyfall.png', 'Spyfall', 'Jogo de cartas social e de dedução onde os jogadores assumem papéis secretos em diferentes locais.', 4, 'Cartas', 'Social', 10, 15, 8, 'Cryptozoic Entertainment', 'Jogo fácil de aprender com muita interação.', 'Cartas de alta qualidade e ótima experiência de jogo.'),
('stuffedfables.png', 'Stuffed Fables', 'Jogo de tabuleiro cooperativo onde os jogadores assumem o papel de brinquedos que ganham vida.', 3, 'Tabuleiro', 'Aventura', 8, 60, 4, 'Plaid Hat Games', 'Componentes de alta qualidade com miniaturas detalhadas.', 'Narrativa envolvente e experiência cooperativa.'),
('junglespeed.png', 'Jungle Speed', 'Jogo de cartas rápido onde os jogadores competem para pegar o totem quando cartas iguais são reveladas.', 3, 'Cartas', 'Festa', 7, 15, 10, 'Asmodee', 'Jogo fácil de aprender com muita ação.', 'Componentes duráveis e ótima experiência de jogo.'),
('team3.png', 'Team 3', 'Jogo de cartas cooperativo onde os jogadores trabalham juntos para completar desafios.', 3, 'Cartas', 'Cooperativo', 8, 30, 6, 'Lúdilo', 'Jogo com regras simples e partidas dinâmicas.', 'Componentes de alta qualidade e ótima experiência de jogo.'),
('foideproposito.png', 'Foi de Propósito', 'Jogo de cartas estratégico onde os jogadores competem para completar objetivos secretos.', 5, 'Cartas', 'Estratégia', 10, 30, 6, 'Red Glove', 'Jogo fácil de aprender com muita interação.', 'Cartas de alta qualidade e ótima experiência de jogo.'),
('theresistance.png', 'The Resistance', 'Jogo de cartas social e de dedução onde os jogadores assumem papéis secretos.', 5, 'Cartas', 'Social', 10, 30, 10, 'Indie Boards & Cards', 'Jogo fácil de aprender com muita interação.', 'Cartas de alta qualidade e ótima experiência de jogo.'),
('master.png', 'Master', 'Jogo de cartas estratégico onde os jogadores competem para se tornar o mestre do jogo.', 5, 'Cartas', 'Estratégia', 10, 30, 6, 'Lúdilo', 'Jogo com regras simples e partidas dinâmicas.', 'Componentes de alta qualidade e ótima experiência de jogo.'),
('imagine.png', 'Imagine', 'Jogo de cartas criativo onde os jogadores usam transparências com símbolos para representar palavras.', 3, 'Cartas', 'Criatividade', 8, 30, 6, 'Repos Production', 'Jogo fácil de aprender com muita criatividade.', 'Componentes de alta qualidade e ótima experiência de jogo.'),
('loveletter.png', 'Love Letter', 'Jogo de cartas rápido e estratégico onde os jogadores competem para entregar uma carta de amor à princesa.', 3, 'Cartas', 'Estratégia', 8, 20, 4, 'Cranio Creations', 'Jogo fácil de aprender com muita interação.', 'Cartas de alta qualidade e ótima experiência de jogo.'),
('misty.png', 'Misty', 'Jogo de cartas estratégico onde os jogadores competem para controlar territórios e acumular pontos.', 4, 'Cartas', 'Estratégia', 10, 30, 6, 'Lúdilo', 'Jogo com regras simples e partidas dinâmicas.', 'Componentes de alta qualidade e ótima experiência de jogo.'),
('godofwar.png', 'God of War: O Jogo de Tabuleiro', 'Adaptação do videogame, onde os jogadores assumem o papel de Kratos e Atreus em uma jornada épica.', 5, 'Tabuleiro', 'Aventura', 12, 90, 4, 'CMON Limited', 'Componentes de alta qualidade com miniaturas detalhadas.', 'Narrativa envolvente e experiência cooperativa.'),
('gameoflife.png', 'Game of Life', 'Jogo de tabuleiro clássico onde os jogadores simulam a jornada da vida.', 5, 'Tabuleiro', 'Família', 8, 60, 6, 'Hasbro', 'Um clássico que nunca sai de moda.', 'Ideal para longas sessões de jogo com amigos e família.'),
('sherlock.png', 'Sherlock Express', 'Jogo de cartas rápido onde os jogadores assumem o papel de detetives tentando capturar Moriarty.', 4, 'Cartas', 'Mistério', 8, 20, 6, 'Devir', 'Jogo fácil de aprender com muita interação.', 'Cartas de alta qualidade e ótima experiência de jogo.'),
('combocolor.png', 'Combo Color', 'Jogo de cartas rápido e estratégico onde os jogadores competem para formar combinações de cores e números.', 3, 'Cartas', 'Estratégia', 8, 20, 6, 'Lúdilo', 'Jogo com regras simples e partidas dinâmicas.', 'Componentes de alta qualidade e ótima experiência de jogo.'),
('castleparty.png', 'Castle Party', 'Jogo de tabuleiro estratégico onde os jogadores competem para construir e decorar o castelo.', 4, 'Tabuleiro', 'Estratégia', 8, 60, 4, 'Lúdilo', 'Jogo com regras simples e partidas dinâmicas.', 'Componentes de alta qualidade e ótima experiência de jogo.'),
('tinytowns.png', 'Tiny Towns', 'Jogo de tabuleiro estratégico onde os jogadores assumem o papel de prefeitos de pequenas cidades.', 4, 'Tabuleiro', 'Estratégia', 10, 45, 4, 'Alderac Entertainment Group', 'Componentes de alta qualidade com peças detalhadas.', 'Regras fáceis de aprender e experiência fluida.');
